import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

/**
 * Refresh trade images for all module_articles in an issue.
 *
 * Copies the latest image_url from the linked rss_posts row into
 * module_articles.trade_image_url. This is used after trade card images
 * are regenerated by the rss-combiner, so existing module articles pick
 * up the newly generated images.
 */
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: issueId } = await params

  // Get issue's publication_id for tenant isolation
  const { data: issue, error: issueError } = await supabaseAdmin
    .from('publication_issues')
    .select('id, publication_id')
    .eq('id', issueId)
    .single()

  if (issueError || !issue) {
    return NextResponse.json({ error: 'Issue not found' }, { status: 404 })
  }

  // Fetch all module_articles for this issue with their linked rss_post.image_url
  const { data: articles, error: articlesError } = await supabaseAdmin
    .from('module_articles')
    .select(`
      id,
      article_module_id,
      trade_image_url,
      trade_image_alt,
      ticker,
      rss_post:rss_posts(image_url, image_alt, ticker)
    `)
    .eq('issue_id', issueId)

  if (articlesError) {
    console.error('[recheck-images] Failed to fetch module articles:', articlesError.message)
    return NextResponse.json({ error: articlesError.message }, { status: 500 })
  }

  if (!articles || articles.length === 0) {
    return NextResponse.json({ success: true, results: [], message: 'No module articles for this issue' })
  }

  // Group results by article_module_id for reporting
  const moduleResults = new Map<string, { updated: number; total: number; unchanged: number }>()

  for (const article of articles) {
    const moduleId = article.article_module_id
    if (!moduleResults.has(moduleId)) {
      moduleResults.set(moduleId, { updated: 0, total: 0, unchanged: 0 })
    }
    const stats = moduleResults.get(moduleId)!
    stats.total++

    // rss_post is returned as an array by Supabase when it's a nested select, or object
    const rssPost = Array.isArray((article as any).rss_post)
      ? (article as any).rss_post[0]
      : (article as any).rss_post

    const newImageUrl = rssPost?.image_url || null
    const newImageAlt = rssPost?.image_alt || (article as any).ticker || rssPost?.ticker || null

    // Only update if the image has actually changed
    if (newImageUrl !== article.trade_image_url) {
      const { error: updateError } = await supabaseAdmin
        .from('module_articles')
        .update({
          trade_image_url: newImageUrl,
          trade_image_alt: newImageAlt,
        })
        .eq('id', article.id)

      if (updateError) {
        console.error(`[recheck-images] Failed to update article ${article.id}:`, updateError.message)
      } else {
        stats.updated++
      }
    } else {
      stats.unchanged++
    }
  }

  // Fetch module names for the response
  const moduleIds = Array.from(moduleResults.keys())
  const { data: modules } = await supabaseAdmin
    .from('article_modules')
    .select('id, name')
    .in('id', moduleIds)
    .eq('publication_id', issue.publication_id)

  const moduleNameMap = new Map((modules || []).map(m => [m.id, m.name]))

  const results = Array.from(moduleResults.entries()).map(([moduleId, stats]) => ({
    module: moduleNameMap.get(moduleId) || 'Unknown',
    moduleId,
    matched: stats.updated,
    total: stats.total,
    unchanged: stats.unchanged,
  }))

  return NextResponse.json({
    success: true,
    results,
  })
}
