import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

/**
 * Refresh trade images for all module_articles in an issue.
 *
 * Resolves the current trade card image for each article by:
 *   1. Looking up the latest image_url in congress_trades matching the ticker
 *   2. Verifying the underlying file actually exists in Supabase storage
 *      (previously this endpoint could copy stale URLs pointing to deleted files)
 *   3. Falling back to rss_posts.image_url if no valid congress_trades image
 *
 * Used after trade card images are regenerated by the rss-combiner workflow,
 * so existing module articles pick up the newly generated images.
 */
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: issueId } = await params

  // Get issue's publication_id for tenant isolation
  const { data: issue, error: issueError } = await supabaseAdmin
    .from('publication_issues')
    .select('id, publication_id')
    .eq('id', issueId)
    .single()

  if (issueError || !issue) {
    return NextResponse.json({ error: 'Issue not found' }, { status: 404 })
  }

  // Fetch all module_articles for this issue with their linked rss_post fallback
  const { data: articles, error: articlesError } = await supabaseAdmin
    .from('module_articles')
    .select(`
      id,
      article_module_id,
      trade_image_url,
      trade_image_alt,
      ticker,
      rss_post:rss_posts(image_url, image_alt, ticker)
    `)
    .eq('issue_id', issueId)

  if (articlesError) {
    console.error('[recheck-images] Failed to fetch module articles:', articlesError.message)
    return NextResponse.json({ error: articlesError.message }, { status: 500 })
  }

  if (!articles || articles.length === 0) {
    return NextResponse.json({ success: true, results: [], message: 'No module articles for this issue' })
  }

  // Build a map of ticker → valid trade card image URL from congress_trades.
  // Only include tickers whose underlying file actually exists in Supabase Storage
  // (previously this endpoint could copy stale URLs pointing to deleted files).
  // Collect tickers from both module_articles and their linked rss_posts
  const tickers = Array.from(new Set(
    articles.flatMap(a => {
      const rssPost = Array.isArray((a as any).rss_post) ? (a as any).rss_post[0] : (a as any).rss_post
      return [a.ticker, rssPost?.ticker].filter(Boolean)
    })
  )) as string[]
  const validImageByTicker = new Map<string, string>()

  if (tickers.length > 0) {
    // Fetch all congress_trades rows for these tickers with non-null image_url.
    // Order by most recent so the first per ticker wins.
    const { data: tradeRows, error: tradeError } = await supabaseAdmin
      .from('congress_trades')
      .select('id, ticker, image_url, quiver_upload_time')
      .in('ticker', tickers)
      .not('image_url', 'is', null)
      .order('quiver_upload_time', { ascending: false, nullsFirst: false })

    if (tradeError) {
      console.error('[recheck-images] Failed to query congress_trades:', tradeError.message)
      return NextResponse.json({ error: 'Failed to query trade images' }, { status: 500 })
    }

    // Verify file existence via the Supabase Storage API.
    // Fetch all files under the st/t/ prefix once and build a lookup set.
    const existingFiles = new Set<string>()
    let offset = 0
    const pageSize = 1000
    let storageListFailed = false
    while (true) {
      const { data: files, error: listError } = await supabaseAdmin.storage
        .from('img')
        .list('st/t', { limit: pageSize, offset })

      if (listError) {
        console.error('[recheck-images] Storage list error:', listError.message)
        storageListFailed = true
        break
      }
      if (!files || files.length === 0) break
      for (const f of files) existingFiles.add(f.name)
      if (files.length < pageSize) break
      offset += pageSize
    }

    // If storage listing failed and we got no files, don't overwrite existing
    // trade_image_url values — it's safer to keep them than wipe them.
    if (storageListFailed && existingFiles.size === 0 && (tradeRows || []).length > 0) {
      console.warn('[recheck-images] Storage listing failed, skipping image updates to preserve existing URLs')
      return NextResponse.json({
        success: false,
        error: 'Storage listing failed — image URLs not updated to avoid data loss. Try again.',
        results: [],
      })
    }

    // Walk rows in order — first matching ticker with a verified file wins
    for (const row of tradeRows || []) {
      if (validImageByTicker.has(row.ticker)) continue
      if (existingFiles.has(`${row.id}.png`)) {
        validImageByTicker.set(row.ticker, row.image_url)
      }
    }
  }

  // Group results by article_module_id for reporting
  const moduleResults = new Map<string, { updated: number; total: number; unchanged: number }>()

  for (const article of articles) {
    const moduleId = article.article_module_id
    if (!moduleResults.has(moduleId)) {
      moduleResults.set(moduleId, { updated: 0, total: 0, unchanged: 0 })
    }
    const stats = moduleResults.get(moduleId)!
    stats.total++

    // rss_post is returned as an array by Supabase when it's a nested select, or object
    const rssPost = Array.isArray((article as any).rss_post)
      ? (article as any).rss_post[0]
      : (article as any).rss_post

    // Prefer a verified congress_trades image (try article ticker, then rss_post ticker),
    // then fall back to rss_posts.image_url
    const articleTicker = article.ticker || rssPost?.ticker || null
    const resolvedImage =
      (articleTicker && validImageByTicker.get(articleTicker)) ||
      rssPost?.image_url ||
      null

    const newImageAlt = rssPost?.image_alt || (article as any).ticker || rssPost?.ticker || null

    // Only update if the image has actually changed
    if (resolvedImage !== article.trade_image_url) {
      const { error: updateError } = await supabaseAdmin
        .from('module_articles')
        .update({
          trade_image_url: resolvedImage,
          trade_image_alt: newImageAlt,
        })
        .eq('id', article.id)

      if (updateError) {
        console.error(`[recheck-images] Failed to update article ${article.id}:`, updateError.message)
      } else {
        stats.updated++
      }
    } else {
      stats.unchanged++
    }
  }

  // Fetch module names for the response
  const moduleIds = Array.from(moduleResults.keys())
  const { data: modules } = await supabaseAdmin
    .from('article_modules')
    .select('id, name')
    .in('id', moduleIds)
    .eq('publication_id', issue.publication_id)

  const moduleNameMap = new Map((modules || []).map(m => [m.id, m.name]))

  const results = Array.from(moduleResults.entries()).map(([moduleId, stats]) => ({
    module: moduleNameMap.get(moduleId) || 'Unknown',
    moduleId,
    matched: stats.updated,
    total: stats.total,
    unchanged: stats.unchanged,
  }))

  return NextResponse.json({
    success: true,
    results,
  })
}
