import { NextResponse } from 'next/server'
import { withApiHandler } from '@/lib/api-handler'
import { supabaseAdmin } from '@/lib/supabase'
import { resolveIssueTradeImages } from '@/lib/article-modules/resolve-issue-trade-images'

/**
 * Refresh trade images for all module_articles in an issue.
 *
 * Resolution is delegated to `resolveIssueTradeImages`, which matches each
 * article strictly by its (ticker, member_name, transaction_type) tuple against
 * `congress_trades.image_url` (verifying the PNG exists in Storage), with no
 * ticker-only or rss_posts fallback. A missing image beats a wrong one.
 *
 * Used after trade card images are regenerated by the rss-combiner workflow,
 * so existing module articles pick up the newly generated images.
 */
export const POST = withApiHandler(
  { authTier: 'authenticated', logContext: 'campaigns/[id]/article-modules/recheck-images' },
  async ({ params, logger }) => {
    const issueId = params.id

    const resolution = await resolveIssueTradeImages(issueId)

    if (!resolution.ok) {
      return NextResponse.json(
        { success: false, error: resolution.error, results: [] },
        { status: resolution.status ?? 500 }
      )
    }

    if (resolution.results.length === 0) {
      return NextResponse.json({ success: true, results: [], message: 'No module articles for this issue' })
    }

    // Map module ids → names for a friendlier response (tenant-scoped).
    const moduleIds = resolution.results.map((r) => r.moduleId)
    const { data: modules } = await supabaseAdmin
      .from('article_modules')
      .select('id, name')
      .in('id', moduleIds)
      .eq('publication_id', resolution.publicationId!)

    const moduleNameMap = new Map((modules || []).map((m) => [m.id, m.name]))

    const results = resolution.results.map((r) => ({
      module: moduleNameMap.get(r.moduleId) || 'Unknown',
      moduleId: r.moduleId,
      matched: r.matched,
      cleared: r.cleared,
      unchanged: r.unchanged,
      total: r.total,
    }))

    logger.info(
      { issueId, modules: results.length, matched: results.reduce((s, r) => s + r.matched, 0) },
      'Rechecked trade images'
    )

    return NextResponse.json({ success: true, results })
  }
)
