import { supabaseAdmin } from '@/lib/supabase'

/**
 * Combined Step 3: Generate Articles
 * NOTE: Article generation now handled by process-rss-workflow.ts -> module-articles.ts
 * This step only counts generated module articles for logging.
 */
export async function executeStep3(issueId: string) {
  // Module articles are generated by process-rss-workflow.ts
  // Just count what was generated for logging
  const { count } = await supabaseAdmin
    .from('module_articles')
    .select('id', { count: 'exact', head: true })
    .eq('issue_id', issueId)

  const articlesCount = count || 0
  console.log(`[Step 3/4] Complete: ${articlesCount} module articles`)
  return { articlesCount }
}
